social and donations pull request
HarvardWestlake/Wolvercoin pull request #116
Opened 2023-01-17 22:58 UTC by benjihamm

2023-01-17 23:02 UTC, monkeymatt2023 approved these changes
All tests look good!

2023-01-18 03:06 UTC, ZachRossen requested changes
Don't forget parenthesis after calling getters.

2023-01-18 17:42 UTC, benjihamm commented
I have parenthesis after calling my getters. Could you check again?

2023-01-18 19:02 UTC, ZachRossen approved these changes

2023-01-19 17:26 UTC, merged